#### Last couple of features of lists before we proceed to conditional statements

In [ ]:
# range() is a function that generates a sequence of numbers

nums = list(range(5))
print(nums)

nums1 = list(range(5,16))
print("\nThis is the second list", nums1)

nums2 = list(range(0,100,10))
print("\nThis is the third list", nums2)

[0, 1, 2, 3, 4]

This is the second list [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

This is the third list [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]


### Slicing Lists

In [ ]:
nums = list(range(0,100,5))
print("Original list: ", nums)
print('\nFirst 3 elements of list:', nums[0:3]) # print 0,1,2 index. Upto 3, not including 3.
print('\nEverything 4th element onwards:', nums[4:])
print('\nLast item of list:', nums[-1])
print('\nBackwards list smun:', nums[::-1])
print('\nFirst up till 5th element with step-size 2:', nums[1:5:2])

Original list:  [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

First 3 elements of list: [0, 5, 10]

Everything 4th element onwards: [20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

Last item of list: 95

Backwards list smun: [95, 90, 85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10, 5, 0]

First up till 5th element with step-size 2: [5, 15]


## Conditional Statements, Looping

In [ ]:
'''The BDFL (Benevolent Dictator for Life) has a good sense of humor. Each package that you install needs to be imported before you can use it.
# Look what happens when you import a package called 'this'. It prints the Zen of Python - a rulebook for writing IF statements'''

import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


## Let us start with IF loops.

Before that, we need to understand Indentation in Python

Indentation has a very specific role in Python and is important!

It is used as alternative to parenthesis, and getting it wrong will cause errors.
IF Statements and Indentation
- The syntax for control structures in Python use _colons_ and _indentation_.


```
# This is formatted as code

if condition1:
  do something
elif condition2:
  do something else
else:
  do this last thing
```




In [ ]:
y = -2
x = 10
if x > 0:
    print ('x is strictly positive')
    print (x)
# print ('Finished.', x, y)

if y < 0:
    print ('y is strictly negative, its value is: ', y)
    print (y)

x is strictly positive
10
y is strictly negative, its value is:  -2
-2


In [ ]:
print("What is the temperature outside?")
temperature = int(input())

if temperature < -10 or temperature > 30:
    print("Extreme weather of", temperature, "degrees Celsius")

print("What is the price of this item?")
value = int(input())

if not value > 10:
    print("value not greater than 10")

print("What is your age?")
age = int(input())

print("What country do you belong to?")
country = input()

if int(age) >= 18 and country == "Germany":
    print("You may drink alcohol")

What is the temperature outside?
5
What is the price of this item?
7
value not greater than 10
What is your age?
19
What country do you belong to?
usa


In [ ]:
# print the price of eggs as $5 if you live in New York state and it is currently winter season

state = input()
season = input()

if state == "New York" and season == "winter":
    print("Price of eggs: $5")

New York
winter
Price of eggs: $5


## Conditional Statements

- `if` statements enable logic.
- `elif` give additional conditions.
- `else` gives what to do if other conditions are not met.

In [ ]:
purchase = float(input("Price at which you purchased bitcoin: "))
current = float (input ("Current price of bitcoin: "))

if current < purchase*1.2 and current >= purchase:
  print("Consider holding on a bit longer as your profit is only ", current - purchase,  "$ per bitcoin.")
elif current >= purchase*1.2:
  print("Worth selling as you will make", current - purchase, "$ per bitcoin.")
else:
  print('Not worth selling right now. Your loss is: $', current - purchase, ' per bitcoin.')

Price at which you purchased bitcoin: 50
Current price of bitcoin: 55
Consider holding on a bit longer as your profit is only  5.0 $ per bitcoin.


In [ ]:
x = -11
y = 0
if x > 0:
    print ('x is greater than 0')
    if y > 0:
        print ('& y is also greater than 0')
    elif y<0:
        print ('& y is less than 0')
    else:
        print ('& y is equal to 0')
print ("x: ",x)
print ('Finished.')

x:  -11
Finished.


In [ ]:
x = -81
y = 0
if x > 0:
    print ('x is greater than 0')
if y > 0:
    print ('& y is also greater than 0')
elif y<0:
    print ('& y is less than 0')
else:
    print ('& y is equal to 0')
print ("x: ",x)
print ('Finished.')

& y is equal to 0
x:  -81
Finished.


# Try printing each of these. Play around with the value of x



In [ ]:
x = 4
x != 5
x > 0
x==5

False

## Python Conditionals (Alt Syntax)

In [ ]:
x=0
if x > 0:
  z = 5
else:
  z = 0
print(z) # how we would generally run this code

0


In [ ]:
x=0
z = 5 if x > 0 else 0
print(z)

0


In [ ]:
# This is a form of if statement called ternary conditional operator
x=1
#The first value is the value if the conditional is false
z=(0, 5)[x>0]
print(z)

5


## FOR Statement

Enables us to iterate over contents of lists.

In [ ]:
#Here we are iterating on lists.
sum=0
for ad in [10, 2, 36]:
    sum+=ad    #This is short hand for sum = sum+ad
    print(sum)

for country in ['England', 'Spain', 'India']:
    print(country)

10
12
48
England
Spain
India


In [ ]:
products = ["banana", "apple", "squash"]

for item in products:
    print("Our best selling product this week is, " + item + "!")

Our best selling product this week is, banana!
Our best selling product this week is, apple!
Our best selling product this week is, squash!


In [ ]:
x=[0,1,2]
y=['a','b','c','j']
#Nested for loops
for d in x:
    for f in y:
        print(d,f)

0 a
0 b
0 c
0 j
1 a
1 b
1 c
1 j
2 a
2 b
2 c
2 j


In [ ]:
for i in range(10):
    print(i*3)

0
3
6
9
12
15
18
21
24
27


In [ ]:
multiple_three = []
for i in range(11):
    multiple_three.append(i*3)
print(multiple_three)

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30]


In [ ]:
#Range is a built in function that can be passed to a for loop
#https://docs.python.org/3/library/functions.html#func-range
#Range accepts a number and a (start/stop/step) like the arrange command.
z=range(5)
# print(z, type(z))
#Range
for i in z:
    print('Print five')
for i in range(4):
    print('Print four more')
for i in range(5,20,2):
    print('i: %d is the value' % (i))
    # print(f'i:{i}  is the 2nd value' ) #This is an alternate way of embedding values in text.

Print five
Print five
Print five
Print five
Print five
Print four more
Print four more
Print four more
Print four more
i: 5 is the value
i: 7 is the value
i: 9 is the value
i: 11 is the value
i: 13 is the value
i: 15 is the value
i: 17 is the value
i: 19 is the value


In [ ]:
#This is the long way of building lists.
L = []
for n in range(5,15):
    L.append(n ** 2)
L

[25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [ ]:
#With list comprehension.
L=[n ** 2 for n in range(5,15)]
L

[25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [ ]:
# Print all negative numbers in a list

mylist = [2, 5, -3, 8, 1, -5, -8]
neglist = []
for i in mylist:
    if i < 0:
        neglist.append(i)
print(neglist)


# With list comprehensions
neglist2 = [i for i in mylist if i < 0]
print(neglist2)

[-3, -5, -8]
[-3, -5, -8]


In [ ]:
#Any actions are on left side, any conditionals on right side
[i for i in range(20) if i % 3 == 0]

[0, 3, 6, 9, 12, 15, 18]

### Multiple Interators
- Iterating on multiple values

In [ ]:
[(i, j) for i in range(2) for j in range(3)]

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2)]

### Dictionary Comprehension


In [ ]:
#We can change it to a dictionary by just changing the brackets and adding a colon.
{n:n**2 for n in range(6)}

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

## While Loops
- Performs a loop while a conditional is True.
- Doesn't auto-increment.


In [1]:
x = 1
sum=0
while x<10:
    print ("Printing x= %d sum= %d" % (x, sum))
    x += 1
    sum+=10

Printing x= 1 sum= 0
Printing x= 2 sum= 10
Printing x= 3 sum= 20
Printing x= 4 sum= 30
Printing x= 5 sum= 40
Printing x= 6 sum= 50
Printing x= 7 sum= 60
Printing x= 8 sum= 70
Printing x= 9 sum= 80


In [2]:
a = 1
while a<2000:
  print(a)
  a = a*2

1
2
4
8
16
32
64
128
256
512
1024


In [3]:
a = 1

while True:
    a = a * 2
    print(a)
    if (a > 1000):
        break

2
4
8
16
32
64
128
256
512
1024


In [4]:
n = 0
while True: # execute indefinitely print ("Executing while loop")
  if n == 5: # stop loop if n is 5
    break
  n = n + 1
  print ("Finished while loop", n)


Finished while loop 1
Finished while loop 2
Finished while loop 3
Finished while loop 4
Finished while loop 5


## Recoding Variables/Creating Features with `for/if`
- Often we want to recode data applying some type of conditional statement to each value of a series, list, or column of a data frame.
- [Regular Expressions](https://docs.python.org/3/howto/regex.html) can be useful in recoding

In [5]:
#Titanic Preview Women and Children first

gender=['Female', 'Female','Female', 'Male', 'Male', 'Male' ]
age=[75, 45, 15, 1, 45, 4 ]
name = ['Sally White', 'Susanna Petrovsky', 'Samantha Russ', 'Finn Patrick', 'Johnny Cash', 'Pep Guardiola']
survived=[]
for i in range(len(gender)):
    if gender[i]=='Female':
        survived.append('Survived')
    else:
        survived.append('Died')
print(survived)


['Survived', 'Survived', 'Survived', 'Died', 'Died', 'Died']


In [12]:
young=[]
for i in range(len(age)):
    if age[i]>=20:
        young.append('adult')
    else:
        young.append('child')
print(young)



['adult', 'adult', 'child', 'child', 'adult', 'child']


In [13]:
# prompt: gender=['Female', 'Female','Female', 'Male', 'Male', 'Male' ]
# age=[75, 45, 15, 1, 45, 4 ]

import pandas as pd

data = {'gender': gender, 'age': age}
df = pd.DataFrame(data)
df


gender  age
0  Female   75
1  Female   45
2  Female   15
3    Male    1
4    Male   45
5    Male    4

In [14]:
# create a list that has survived if gender is female and died if otherwise using list comprehensions

survived2 = [('Survived' if gender[i]=='Female' else 'Died') for i in range(len(gender))]
print('\n',survived2)


 ['Survived', 'Survived', 'Survived', 'Died', 'Died', 'Died']


### Let us now open a Text File that is in our computer.
NOTE: This is not possible on Colab as Colab does not access files in your C drive. I have still provided you the code to use should you wish to run code on a different IDE instead.

In [15]:
### Will not work on Google Colab
f = open('/Users/NAME/FOLDER/class.txt', 'r')
f.read()

FileNotFoundError: [Errno 2] No such file or directory: '/Users/NAME/FOLDER/class.txt'

In [16]:
import base64
import requests

master = "https://raw.githubusercontent.com/Jainu-s/urldata/master/al/abescoldbeer.com.txt"
req = requests.get(master)
req = req.text
print(req)

stock beers abe's cold beer best selection lehigh valley specials promotions latest facebook diversify palette sixpoint puff weyerbacher finally legal bourbon barrel aged stout cocoa vanilla high watermelon troegs crimson pistil ipa brewed hibiscus flowers avery tequilacerbus bell's oberon victory monkey ballast point rose einstok icelandic arctic berry ale white cans summer monarchy methusalem holunderheimer johannisburger dortmunder altbier save beers years like oldest person according flying monkey's chocolate manifesto triple milk fegle'y blueberry belch evil twin lamp goose island lolita dog rental radler grapfruit passion fruit funk tumble weed plenty places beer established lot longer abe’s supermarkets trying crack market customers abe’s…sometimes far miles that’s right… different beers available know real stock largest best selection world we’ll glad special order mention massive filter brand country united states australia asia belgium canada europe kingdom france germany ita

In [17]:
# https://github.com/Jainu-s/urldata/tree/master/al
# https://github.com/JyothsnaGH/PythonforFinance/blob/main/clifford.txt
master = "https://raw.githubusercontent.com/JyothsnaGH/PythonforFinance/main/clifford.txt"
req = requests.get(master)
req = req.text
print(req)

Lady Anne Clifford, Countess of Dorset, Pembroke and Montgomery, suo jure 14th Baroness de Clifford (30 January 1590 – 22 March 1676)[3] was an English peeress. In 1605 she inherited her father's ancient barony by writ and became suo jure 14th Baroness de Clifford. She was a patron of literature and as evidenced by her diary and many letters was a literary personage in her own right. She held the hereditary office of High Sheriff of Westmorland which role she exercised from 1653 to 1676.[4]

Early years
Lady Anne was born on 30 January 1590 in Skipton Castle, and was baptised the following 22 February in Holy Trinity Church in Skipton in the West Riding of Yorkshire.[4] She was the only surviving child and sole heiress of George Clifford, 3rd Earl of Cumberland (1558–1605) of Appleby Castle in Westmorland and of Skipton Castle, by his wife, Lady Margaret Russell, daughter of Francis Russell, 2nd Earl of Bedford.[4]

Her parents' marriage was soured by the deaths of Anne's two elder bro

In [18]:
!git clone https://github.com/JyothsnaGH/PythonforFinance.git

Cloning into 'PythonforFinance'...
remote: Enumerating objects: 76, done.
remote: Counting objects: 100% (76/76), done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 76 (delta 40), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (76/76), 44.00 KiB | 850.00 KiB/s, done.
Resolving deltas: 100% (40/40), done.


## Overview of Numpy

- NumPy is a free, open-source Python library that provides support for multi-dimensional arrays and mathematical operations.
- Numpy is often useful for data science.
- A NumPy array is a powerful data structure in Python provided by the NumPy library.
- You can slice an array just like a list.
- Numpy is imported as `np`.
- Unlike lists, all elements in a NumPy array must be of the same data type.



In [19]:
import numpy as np
a = np.array([0, 10, 22, 35, 47, 52, 69])
print('Print the entire array:', a)
print('Print the first value:', a[0])
print('Print the first three value:', a[0:3])
print('Print the last value of a numpy array:', a[-1])


Print the entire array: [ 0 10 22 35 47 52 69]
Print the first value: 0
Print the first three value: [ 0 10 22]
Print the last value of a numpy array: 69


In [20]:
# print the largest value of a numpy array
a = np.array([0, 110, 242, -65, -4, 435, -567, 100, 99])


## Arrays and Functions
- A really powerful aspect of arrays is the capability to do calculations over arrays.
- List of Numpy functions: https://numpy.org/doc/2.1/reference/routines.math.html


In [23]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b1=10*a
b2=np.multiply(10,a)
c=a+b1 # c2=np.add(a,b1) #This is an alternate way of adding
d=np.log(a)
e=np.sqrt(a)
f=a**2  #This squares the value.

np.square([-1j, 1])
print('Print a:', a)
print('Print b1:', b1)
print('Print b2:', b2)
print('Print c:', c)
print('Print d:', d)
print('Print e:', e)
print('Print f:', f)

Print a: [1 2 3 4 5 6]
Print b1: [10 20 30 40 50 60]
Print b2: [10 20 30 40 50 60]
Print c: [11 22 33 44 55 66]
Print d: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
Print e: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
Print f: [ 1  4  9 16 25 36]


## Slicing Single Dimension Numpy Arrays
- Slicing arrays includes  three numbers `a[start:stop:step]` but not all are required.
- Defaults: start =0, end =last and step is 1.
- To print the entire array, leave start/stop/step blank`a[::]`


In [24]:
e= np.arange( 0, 15, 1 )
print(e)
#[start:end:step]


print("This is the start, end, and step:",e[2:9:3])
print("Print every other:",e[::2])
print("Print starting at 2 and ending at 9, default step 1:",e[2:9])
print("Print all:",e[::])
print("Print all:",e[:])
print("Print all:",e)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
This is the start, end, and step: [2 5 8]
Print every other: [ 0  2  4  6  8 10 12 14]
Print starting at 2 and ending at 9, default step 1: [2 3 4 5 6 7 8]
Print all: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Print all: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Print all: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Creating and Manipulating Numpy Arrays
- The arrange function will generate an array.
- Reshape changes the structure of the array to n rows and m columns.
    `a=a.reshape(n, m)`
-`ones` will create an array with all ones and `zeros` with all zeros.
- Reshaping can get it in the appropriate structure, but make sure that the size fits the appropriate dimensions.

In [28]:
import numpy as np
#a = np.arange(15)
#print(a)
#a2 = np.arange( 0, 15, 1) #Alternate specification with np.arrange(start, end, step)
#print(a2)
#a=a.reshape(3, 5)
#print(a)
b= np.ones(shape=(3, 5), dtype=float)
print(b)
c= np.zeros(shape=(3, 5), dtype=int)
print('c', c)
d= np.full((3, 5), 4, dtype=int)
print('d', d)
e= np.arange( 0, 1.5, .1 ).reshape(3,5)  #String together creations and reshaping. Also can use decimals.
print(e)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
c [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
d [[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]
[[0.  0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8 0.9]
 [1.  1.1 1.2 1.3 1.4]]


In [29]:
e= np.arange( 0, 1.5, .1 ).reshape(3,5)

## Generating Random Numpy Data
- This is often useful, and we will be using it to demonstrate some initial techniques.
- Often you want random but repeatable results, so that for example a test could have a consistent average on a random array. For this we need to set a seed. You only have to do this once.



In [30]:

a = np.random.uniform(50, 150, 10)  #Between 50-150, generate 10 variables from uniform
b = np.random.standard_normal(10)   #With mean 0 and standard deviation 1
print(a)
print(b)



[ 88.85379999 106.29746117 118.28055732  50.0985234  119.28147265
  91.85079741 100.60680565  92.95073924 115.48172356 130.35407671]
[-0.6532238   0.37152642  1.23917473 -1.25197285  0.60271041  0.55262541
 -0.31106375  0.08163154  1.27958386  1.03835656]


## Combining Numpy Arrays
- `concatenate` will string a list of numpy arrays together `np.concatenate([a,b])`
- `vstack` will stack numpy arrays
- Defaults: start =0, end =last and step is 1.
- To print the entire array, leave start/stop/step blank`a[::]`

In [31]:
a = np.arange(5)
b=np.concatenate([a,a])
c=np.vstack([a,a])
d=np.hstack([a,a])
print('a:',a,'\nb:',b,'\nc:',c,'\nd:',d)


a: [0 1 2 3 4] 
b: [0 1 2 3 4 0 1 2 3 4] 
c: [[0 1 2 3 4]
 [0 1 2 3 4]] 
d: [0 1 2 3 4 0 1 2 3 4]


## Numpy Arrays From External Datasets
- We can take a list from an external dataset and change it to an numpy array.

In [32]:
# let's download the iris dataset.

!wget https://raw.githubusercontent.com/JyothsnaGH/PythonforFinance/main/files/iris.csv

--2025-01-30 22:37:55--  https://raw.githubusercontent.com/JyothsnaGH/PythonforFinance/main/files/iris.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2734 (2.7K) [text/plain]
Saving to: ‘iris.csv’

iris.csv            100%[===================>]   2.67K  --.-KB/s    in 0s      

2025-01-30 22:37:55 (36.8 MB/s) - ‘iris.csv’ saved [2734/2734]



In [40]:
import csv
csv_file = csv.reader(open('iris.csv', newline=''), delimiter=',')

data=[]
header = next(csv_file) #
for row in csv_file:
    data.append(row)  # add each row to data
data = np.array(data)
#print(data)

## Slicing 2 Dimensional Numpy Arrays
- We can slice arrays with `array[row, column]` were row and column each include the (start:stop:step) like in arrays
- We can sepecify the type with the `.astype(np.float_)`
- For a full list of Numpy types, see [documentation](http://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html)
- If we create a one dimensional array from 2 dimensional numpy array, it will also be a numpy array of same type.


In [34]:
#We can slice the array several different ways and generate new variables.

irisdata=data[0::,0:4:].astype(np.float_)  #This will select only the first 4 columns and change the type to float
irisdata=data[:,0:4].astype(np.float_)
iristype=data[0:,4:5] # selecting all rows, only column 4, which is the type (virginica).
# print(irisdata,'\n',iristype)

In [46]:
#get the first 20 columns and first 3 dolunms of data as string
iristy=data[0:20,0:3].astype(np.str_)
#iristy



In [53]:
#This can be used to select column 1 and assign to new variable.
# Find the sum of column 1
newvariable=irisdata[::,0:1:]

#This can be used to select column 1 and assign to new variable.
# Find the sum of column 1
newvariable=irisdata[::,0:1:]

#This will sum up column 0
final=irisdata[::,0:1:].sum() # alternative
final2=irisdata[:,0:1].sum() # much cleaner
type(newvariable)
#print(newvariable)
print(final)
print(final2)
print(final)
print(final2)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U3'), dtype('<U3')) -> None

In [36]:
#  mean of column 1
print('mean:', irisdata[::,0:1:].mean())
irisdata[:,0:1].mean()


mean: 5.843333333333334


5.843333333333334

In [ ]:
# mean of row 3
irisdata[2:3,:].mean()

## UCI Machine Learning Data Repository

We can download a few datasets (suitable for machine learning purposes) using the UC Irvine Machine Learning Repository. Check this [link](https://archive.ics.uci.edu/) out for other datasets.

The iris.csv dataset is automatically available on this website. The cool thing is, we do not need to download the csv file Github - we can load it directly from the UCI archive!*italicized text*

In [37]:
!pip install ucimlrepo
from ucimlrepo import fetch_ucirepo

# fetch dataset
iris = fetch_ucirepo(id=53)

# data (as pandas dataframes)
X = iris.data.features
y = iris.data.targets

# metadata
print(iris.metadata)

# variable information
print(iris.variables)


{'uci_id': 53, 'name': 'Iris', 'repository_url': 'https://archive.ics.uci.edu/dataset/53/iris', 'data_url': 'https://archive.ics.uci.edu/static/public/53/data.csv', 'abstract': 'A small classic dataset from Fisher, 1936. One of the earliest known datasets used for evaluating classification methods.\n', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 150, 'num_features': 4, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1936, 'last_updated': 'Tue Sep 12 2023', 'dataset_doi': '10.24432/C56C76', 'creators': ['R. A. Fisher'], 'intro_paper': {'ID': 191, 'type': 'NATIVE', 'title': 'The Iris data set: In search of the source of virginica', 'authors': 'A. Unwin, K. Kleinman', 'venue': 'Significance, 2021', 'year': 2021, 'journal': 'Significance, 2021', 'DOI': '1740-9713.01589', 'URL': 'https://www.semanticscholar.org