# HW 01

### Q1. Write a program to input your age and print whether you are more than or less than a billion seconds old.

In [19]:

 def check_billion_seconds():
    age_in_years = int(input("Enter your age in years: "))
    seconds_per_year= 31536000  # Approximate seconds in a year
    total_seconds = age_in_years * seconds_per_year

    if total_seconds > 1000000000:
        print("You are older than a billion seconds!")
    else:
        print("You are younger than a billion seconds.")

check_billion_seconds()



Enter your age in years: 21
You are younger than a billion seconds.


### Q2. Create a list with 10 names. Print each name with a Good morning greeting with the name using a conditional loop.

For example

`name = ['Ashley', 'Brianna', 'Chetan', 'David', 'Eoin', 'Francois', 'Gemma', 'Hameed', 'Ishaan', 'Joanna']`

Outputs will be 'Good morning, Ashley', 'Good morning, Brianna', and so on.

In [22]:
u = input('Enter Username: ').title()

# Define the list of usernames
usernames = ['Madison', 'Kelly', 'James', 'David', 'Matt', 'Haley', 'Lexi', 'Savannah', 'John', 'Kenzie']

# Iterate through the list of usernames
for user in usernames:
    # Check if the input username is in the list and is 'Madison'
    if u == user and u == 'Madison':
        print('Good morning')
        # If the username is in the list, print 'In list'
        if u in usernames:
            print('Good morning')
    # If the username is not 'Madison' or not in the list, print 'Not in list'
    else:
        print('Good morning')



Enter Username: Madison
Good morning
Good morning
Good morning
Good morning
Good morning
Good morning
Good morning
Good morning
Good morning
Good morning
Good morning


### Q3. Create a list of 15 numbers. Print only those numbers that are divisible by 2.

In [23]:
# Create a list of 15 numbers
numbers = [1, 7, 8, 2, 15, 5, 16, 20, 25, 30, 14, 9, 22, 27, 19]

# Print numbers divisible by 2
print("Numbers divisible by 2:")
for num in numbers:
    if num % 2 == 0:
        print(num)



Numbers divisible by 2:
8
2
16
20
30
14
22


### Q4. Print the squared numbers of a list containing at least 10 numbers with a mix of float, integer, and negative numbers. Use the longer method as well as list comprehension.

You can either generate your own list of 10 numbers or find use a random number generator.

In [24]:
## Enter answer here.

nums = [0,-1.25,15.86,-25]
method1_squares = []

for i in nums:
    method1_squares.append(i**2)

print(method1_squares)

## Now method 2


[0, 1.5625, 251.53959999999998, 625]


### Q5. Write a program to print a year if it is a leap year.

In [25]:
year = int(input())

if year%4 == 0:
    print(year, "is a leap year")
else:
    print(year, "is not a leap year")

2025
2025 is not a leap year


### Q6. Use list comprensions to print all names in a list in upper case.

In [27]:

>>> [x.upper() for x in ["madison", "kely", "john"]]
['Madison', 'Kellly', 'John']

['Madison', 'Kellly', 'John']

### Q7. Question on NUMPY arrays:

a. Create a numpy array called `original` with 100 random numbers. What is the largest number, smallest number, max, min, median, and standard deviation of your array? Print them.

HINT: use `np.random.uniform()`. Check online for the correct syntax. `np.random.rand(100)` will give you 100 random numbers of uniform distribution with mean 0 and standard deviation of 1, while we want a mix of larger numbers/integers.

b. Now create an array called `orig_sqrt` which contains the square roots of the numbers in the original array.

### Q8.  Converting 1D arrays into 2D arrays.

a. Convert your original array of 100 random numbers into a 2-dimensional array called `mat_array` with 20 rows and 5 columns. Print this array.

b. What is the mean of every column in `mat_array`?

c. What is the sum of every row? Create a list of 20 elements that contains the sum of every row in `mat_array`.

d. Create the transpose of `mat_array` and call it `transpose_array`. What are the dimensions of this array now? Again, find the mean of each column and the sum of each row.

### Q9. Array slicing:

a. create a new array which contains the 3rd-10th rows and all columns of `mat_array`. Print.

b. Print a new array which contains the the last 5 rows and the last 2 columns of `mat_array`. What is the dimension of this array?

c. Print a new array which contains the first 3 rows and last 10 columns of `transpose_array`.

In [28]:
import numpy as np

# Create a numpy array with 100 random numbers
original = np.random.rand(100)

# Find the largest number
largest = np.max(original)

# Find the smallest number
smallest = np.min(original)

# Calculate the maximum value
max_value = np.max(original)

# Calculate the minimum value
min_value = np.min(original)

# Calculate the median
median = np.median(original)

# Calculate the standard deviation
std_dev = np.std(original)

# Print the results
print("Largest number:", largest)
print("Smallest number:", smallest)
print("Max:", max_value)
print("Min:", min_value)
print("Median:", median)
print("Standard deviation:", std_dev)



Largest number: 0.993512093700607
Smallest number: 0.03492791613342283
Max: 0.993512093700607
Min: 0.03492791613342283
Median: 0.47514631702520493
Standard deviation: 0.2785582636265857


In [29]:
import numpy as np

original_array = np.array([4, 9, 16, 25])
orig_sqrt = np.sqrt(original_array)

print(orig_sqrt)

[2. 3. 4. 5.]


In [30]:
import numpy as np

# Create an array of 100 random numbers
original_array = np.random.rand(100)

# Reshape the array into a 2D array with 20 rows and 5 columns
mat_array = original_array.reshape(20, 5)

# Print the 2D array
print(mat_array)

[[0.42570989 0.19798062 0.44385734 0.96903186 0.4330495 ]
 [0.40022647 0.30314533 0.83857902 0.07206413 0.71740047]
 [0.70006166 0.27216687 0.91044821 0.3477295  0.57212198]
 [0.8800271  0.09453801 0.70959733 0.62202491 0.45127203]
 [0.27906317 0.0222222  0.8372167  0.32125054 0.14689196]
 [0.4395606  0.93057403 0.41723207 0.85086784 0.67659395]
 [0.5332104  0.75265195 0.01830458 0.36361341 0.17522661]
 [0.23835252 0.61377628 0.35246587 0.77473045 0.02117876]
 [0.32909597 0.00990511 0.28977354 0.88152329 0.09777841]
 [0.75978322 0.10185209 0.89327427 0.58210294 0.33864085]
 [0.52694746 0.10447907 0.10791967 0.61775922 0.25249348]
 [0.98451121 0.14738532 0.55302649 0.79167225 0.14355168]
 [0.20195277 0.01597355 0.97552642 0.47616653 0.40333633]
 [0.75428792 0.49141776 0.59970179 0.76051243 0.77683398]
 [0.71838429 0.16765539 0.74298169 0.53851365 0.91469096]
 [0.88637268 0.51703669 0.59380096 0.8713057  0.49207526]
 [0.67956264 0.25318685 0.59995076 0.89269903 0.40044449]
 [0.92300057 0

In [33]:
import numpy as np

# Assuming 'mat_array' was defined in a previous cell, execute that cell first.
# If not, define it here:
# original_array = np.random.rand(100)
# mat_array = original_array.reshape(20, 5)

# Calculate the mean of the first 2 elements of the 1st column
result = mat_array[0][0:2].mean()  # Changed 'pmat_array' to 'mat_array'

print(result) # Print the result

0.3118452540158329


In [34]:
import numpy as np

# Assuming 'mat' is your 2D NumPy array
mat = np.random.randint(1, 10, size=(20, 5))  # Example 20x5 array

# Calculate the sum of each row
row_sums = mat.sum(axis=1)

# Create a list from the row sums
row_sum_list = row_sums.tolist()

print(row_sum_list)

[28, 22, 21, 34, 24, 29, 29, 23, 23, 30, 19, 16, 19, 17, 40, 32, 19, 28, 19, 21]


In [35]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])

print(f'Original Array:\n{arr1}')

arr1_transpose = arr1.transpose()

print(f'Transposed Array:\n{arr1_transpose}')

Original Array:
[[1 2 3]
 [4 5 6]]
Transposed Array:
[[1 4]
 [2 5]
 [3 6]]


In [36]:
import numpy as np
a = np.array([[1,2,6],[4,5,8],[8,3,5],[6,5,4]])
#Print first column
print(a[:,0])
#Print second row
print(a[1,:])

[1 4 8 6]
[4 5 8]


In [37]:
import numpy as np

# Assuming mat_array is a 2D numpy array
def get_last_rows_cols(mat_array):
    num_rows, num_cols = mat_array.shape

    # Slice the last 5 rows and last 2 columns
    new_array = mat_array[-5:, -2:]

    print("New array:", new_array)
    print("Dimension:", new_array.shape)

    return new_array

# Example usage:
mat_array = np.random.randint(10, size=(10, 5))  # Create a sample array
get_last_rows_cols(mat_array)

New array: [[9 6]
 [0 3]
 [2 8]
 [1 4]
 [6 3]]
Dimension: (5, 2)


array([[9, 6],
       [0, 3],
       [2, 8],
       [1, 4],
       [6, 3]])

In [38]:
import numpy as np

# Create a sample array
array = np.array([[1, 2, 3, 4, 5, 6],
                   [7, 8, 9, 10, 11, 12],
                   [13, 14, 15, 16, 17, 18],
                   [19, 20, 21, 22, 23, 24]])

# Transpose the array
transposed_array = array.T

# Extract the desired portion
new_array = transposed_array[:3, -10:]

print(new_array)

[[ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]]


### Q10. Assume you are inviting 15 friends to your party. You guest list has the following dietary preference.

`diet = ['vegetarian', 'pescetarian', 'vegetarian', 'omnivore', 'pescetarian', 'keto', 'keto', 'vegan', 'omnivore', 'omnivore', 'vegan', 'omnivore', 'keto, 'vegetarian', 'vegan']`

Their ages are as follows:

`age = [21, 20, 19, 25, 27, 18, 23, 25, 19, 22, 20, 20, 23, 21, 24]`

Create a list called `menu` which will contain 'veg. fried rice with whiskey' for vegans and vegetarians aged 21 and above,  'veg. fried rice with mocktail' for vegans and vegetarians aged below 21. Follow the same logic and assign fish and white wine to pescetarians of legal age (and fish with mocktail to those below 21). Keto and omnivore guests above 21 will have 'steak and red wine'. Complete the series with the appropriate drink for underage guests.

In [39]:
diet = ['vegetarian', 'pescetarian', 'vegetarian', 'omnivore', 'pescetarian', 'keto', 'keto', 'vegan', 'omnivore', 'omnivore', 'vegan', 'omnivore', 'keto', 'vegetarian', 'vegan']
age = [21, 20, 19, 25, 27, 18, 23, 25, 19, 22, 20, 20, 23, 21, 24]

menu = []
for i in range(len(diet)):
    if diet[i] in ['vegetarian', 'vegan']:
        if age[i] >= 21:
            menu.append('veg. fried rice with whiskey')
        else:
            menu.append('veg. fried rice with mocktail')
    elif diet[i] == 'pescetarian':
        if age[i] >= 21:
            menu.append('fish and white wine')
        else:
            menu.append('fish with mocktail')
    elif diet[i] in ['keto', 'omnivore']:
        if age[i] >= 21:
            menu.append('steak and red wine')
        else:
            menu.append('steak with coke')  # Assuming coke for underage keto/omnivores

print(menu)



['veg. fried rice with whiskey', 'fish with mocktail', 'veg. fried rice with mocktail', 'steak and red wine', 'fish and white wine', 'steak with coke', 'steak and red wine', 'veg. fried rice with whiskey', 'steak with coke', 'steak and red wine', 'veg. fried rice with mocktail', 'steak with coke', 'steak and red wine', 'veg. fried rice with whiskey', 'veg. fried rice with whiskey']
